version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"

  # Maintain dependencies for PHP Dockerfile
  - package-ecosystem: "docker"
    directory: "/php"
    schedule:
      interval: "weekly"
    groups:
      docker-images:
        patterns:
          - "*"
    labels:
      - "dependencies"

  # Maintain dependencies for Nginx Dockerfile
  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "weekly"
    groups:
      docker-images:
        patterns:
          - "*"
    labels:
      - "dependencies"
