kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Chart.Name}}-init"
  namespace: "{{ .Values.global.licensePlate }}{{ .Values.global.sectionTag }}"
data:
  init.sh: |
    #!/bin/bash
    set -e
    source /vault/secrets/postgres
    psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
        -- Create role if it does not exist
        DO \$\$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$PGUSER') THEN
                CREATE ROLE $PGUSER WITH LOGIN PASSWORD '$PGPASSWORD';
            END IF;
        END
        \$\$;

        -- Create user if it does not exist
        DO \$\$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = '$PGUSER') THEN
                CREATE USER $PGUSER WITH PASSWORD '$PGPASSWORD';
            END IF;
        END
        \$\$;

        -- Create database if it does not exist
        SELECT 'CREATE DATABASE limesurvey OWNER $PGUSER'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'limesurvey') \gexec

        GRANT ALL PRIVILEGES ON DATABASE limesurvey TO $PGUSER;
    EOSQL
