---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: limesurvey-data
  namespace: {{ .Values.global.licensePlate }}{{ .Values.global.sectionTag }}
  labels:
{{ include "php.labels.standard" . | indent 4 }}
spec:
  storageClassName: netapp-file-standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
...
