{{- range $volume := .Values.volumes }}
{{- if and (eq $volume.type "persistentVolumeClaim") $volume.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ required "PVC name is required" $volume.name }}
  namespace: {{ $.Values.global.licensePlate }}{{ $.Values.global.sectionTag }}
  labels:
{{ include "nginx.labels.standard" $ | indent 4 }}
spec:
  storageClassName: {{ default "netapp-file-standard" $volume.storageClassName }}
  accessModes:
    - {{ required (printf "PVC accessMode is required for volume %s" $volume.name) $volume.accessMode }}
  resources:
    requests:
      storage: {{ required (printf "PVC size is required for volume %s" $volume.name) $volume.size | quote }}
{{- end }}
{{- end }}
