# Default values for limesurvey Helm chart (test environment)
global:
  licensePlate: cd77be
  sectionTag: -test
  host: "limesurvey-test.apps.silver.devops.gov.bc.ca"
  image:
    tag: test
  vault:
    engine: cd77be-nonprod
    path: "/test"
