# Default values for limesurvey Helm chart (dev environment)
global:
  licensePlate: cd77be
  sectionTag: -dev
  host: "limesurvey-dev.apps.silver.devops.gov.bc.ca"
  image:
    tag: dev

  vault:
    engine: cd77be-nonprod
    path: "/dev"
