---
labels:
  version: latest
  runtime: php
service:
  type: ClusterIP
  port: 9000
ports:
  name: 9000-tcp
  containerPort: 9000
  protocol: TCP
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
