name: Helm - Deploy Chart to OpenShift
run-name: Helm Deployment to ${{ github.event.inputs.environment || 'dev' }} - ${{ github.event.head_commit.message || github.run_number }}
on:
  push:
    branches:
      - main
    paths:
      - "helm/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  helm-deploy:
    environment: ${{ github.event.inputs.environment || 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up OpenShift CLI
        uses: redhat-actions/openshift-tools-installer@v1.13.1
        with:
          oc: "4.16"
          skip_cache: true
      - name: Login to OpenShift
        env:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
          OPENSHIFT_SA_TOKEN: ${{ secrets.OPENSHIFT_SA_TOKEN }}
        run: |
          for i in {1..5}; do
            # Server sometimes doen't respond immediately, retry a few times
            oc login --server=$OPENSHIFT_SERVER --token=$OPENSHIFT_SA_TOKEN --insecure-skip-tls-verify=true && break
            echo "Login failed, retrying in 5 seconds... ($i/5)"
            sleep 5
          done
      - name: Set OpenShift project
        env:
          OPENSHIFT_PROJECT_LICENSE_PLATE: cd77be
        run: |
          oc project $OPENSHIFT_PROJECT_LICENSE_PLATE-${{ github.event.inputs.environment || 'dev' }}
      - name: Add Helm repository
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
      - name: Update & Build Helm dependencies
        run: |
          helm dependency update ./helm
          helm dependency build ./helm
      - name: Deploy Helm chart
        run: |
          helm upgrade --install limesurvey ./helm \
            --values ./helm/values.yaml \
            --values ./helm/values-${{ github.event.inputs.environment || 'dev' }}.yaml
      - name: Verify Deployment
        run: |
          oc rollout status statefulset/limesurvey-postgresql --timeout=180s
          oc rollout status deployment/limesurvey-nginx --timeout=180s
          oc rollout status deployment/limesurvey-php --timeout=180s
