name: Validate Dockerfile and Helm Chart
on:
  push:
    branches:
      - main
    paths:
      - "docker/nginx/Dockerfile"
      - "docker/php/Dockerfile"
      - "helm/**"
  pull_request:
    branches:
      - main
    paths:
      - "docker/nginx/Dockerfile"
      - "docker/php/Dockerfile"
      - "helm/**"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Validate Dockerfile
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --file docker/nginx/Dockerfile --tag limesurvey-openshift/nginx:latest --load ./docker/nginx
          docker buildx build --file docker/php/Dockerfile --tag limesurvey-openshift/php:latest --load ./docker/php
      - name: Set up Helm
        run: helm lint helm
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm dependency build helm
          helm dependency update helm
      - name: Validate Helm Chart
        run: |
          helm template helm --values helm/values.yaml --values helm/values-dev.yaml --output-dir helm/templates
      - name: Helm Dry-Run Install
        run: |
          helm install --dry-run --debug limesurvey helm --values helm/values.yaml --values helm/values-dev.yaml
