name: Helm - Validate and Render Templates
run-name: Helm Validation/CI - ${{ github.event.head_commit.message || github.run_number }}
on:
  push:
    branches:
      - main
    paths:
      - "helm/**"
      - ".github/workflows/helm-ci.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "helm/**"
      - ".github/workflows/helm-ci.yaml"
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update & Build Helm dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm dependency build helm
          helm dependency update helm
      - name: Validate Helm Chart
        run: |
          helm lint helm --values helm/values.yaml --values helm/values-dev.yaml
          helm lint helm --values helm/values.yaml --values helm/values-test.yaml
          helm lint helm --values helm/values.yaml --values helm/values-prod.yaml
          mkdir ~/rendered-templates
          helm template --debug helm --values helm/values.yaml --values helm/values-dev.yaml --output-dir ~/rendered-templates/dev
          helm template --debug helm --values helm/values.yaml --values helm/values-test.yaml --output-dir ~/rendered-templates/test
          helm template --debug helm --values helm/values.yaml --values helm/values-prod.yaml --output-dir ~/rendered-templates/prod
