name: Build Main Images
run-name: "Build main images"

on:
  push:
    branches: [main]

jobs:
  builds:
    name: Build (${{ matrix.package }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    strategy:
      matrix:
        package: [php, nginx]
    timeout-minutes: 10
    steps:
      - name: Set image tag
        id: tag
        run: echo "value=main-$GITHUB_RUN_NUMBER" >> "$GITHUB_OUTPUT"
      - uses: bcgov/actions/builder@4026bfd276b8a5839029106099b13edfb594b2c3 # v0.8.0
        with:
          package: 'limesurvey-${{ matrix.package }}'
          build_context: ${{ matrix.package }}
          build_file: '${{ matrix.package }}/Dockerfile'
          sbom: 'false'
          tags: ${{ steps.tag.outputs.value }}
      - name: Verify built commit
        run: test "$(git -C .builder-context rev-parse HEAD)" = "$GITHUB_SHA"
