name: Nginx Image - Build and Push
run-name: Nginx Docker Build - ${{ github.event.head_commit.message || github.run_number }}
on:
  push:
    branches:
      - main
    paths:
      - "docker/nginx/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Tag the built image as:"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
          - prod
jobs:
  nginx-build-push-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    env:
      ENV_TAG: ${{ github.event.inputs.environment || 'dev' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up OpenShift CLI
        uses: redhat-actions/openshift-tools-installer@v1.13.1
        with:
          oc: "4.16"
          skip_cache: true

      - name: Build Nginx Docker image
        run: |
          docker buildx build --file docker/nginx/Dockerfile --tag limesurvey-openshift/nginx:$ENV_TAG --load docker/nginx
      - name: Login to OpenShift Container Registry
        env:
          OPENSHIFT_SA_USER: ${{ secrets.OPENSHIFT_SA_USER }}
          OPENSHIFT_SA_TOKEN: ${{ secrets.OPENSHIFT_SA_TOKEN }}
          OPENSHIFT_IMAGE_REGISTRY: ${{ secrets.OPENSHIFT_IMAGE_REGISTRY }}
        run: |
          echo $OPENSHIFT_SA_TOKEN | docker login $OPENSHIFT_IMAGE_REGISTRY -u $OPENSHIFT_SA_USER --password-stdin
      - name: Push Nginx image to OpenShift Registry
        env:
          OPENSHIFT_IMAGE_REGISTRY: ${{ secrets.OPENSHIFT_IMAGE_REGISTRY }}
          OPENSHIFT_REPOSITORY: ${{ secrets.OPENSHIFT_REPOSITORY }}
        run: |
          docker tag limesurvey-openshift/nginx:$ENV_TAG $OPENSHIFT_IMAGE_REGISTRY/$OPENSHIFT_REPOSITORY/limesurvey-nginx:$ENV_TAG
          docker push $OPENSHIFT_IMAGE_REGISTRY/$OPENSHIFT_REPOSITORY/limesurvey-nginx:$ENV_TAG
          # Also push as "latest" if environment is dev
          if [ "$ENV_TAG" = "dev" ]; then
            docker tag limesurvey-openshift/nginx:dev $OPENSHIFT_IMAGE_REGISTRY/$OPENSHIFT_REPOSITORY/limesurvey-nginx:latest
            docker push $OPENSHIFT_IMAGE_REGISTRY/$OPENSHIFT_REPOSITORY/limesurvey-nginx:latest
          fi
